import test from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { accessibilityProfile } from "../dist/accessibility.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const wcagDir = join(repoRoot, "reference", "wcag");
const transparentGif =
  "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";

// The WCAG reference is generated by `npm run build:wcag` and committed. Every
// other test here depends on it, so fail loud and early if it is missing.
test("WCAG reference is present (built by npm run build:wcag)", () => {
  for (const file of ["index.md", "glossary.md", "wcag-map.json"]) {
    assert.equal(
      existsSync(join(wcagDir, file)),
      true,
      `reference/wcag/${file} missing — run npm run build:wcag`,
    );
  }
});

test("WCAG map is consistent and every criterion links to a real file", async () => {
  const map = JSON.parse(await readFile(join(wcagDir, "wcag-map.json"), "utf8"));
  const criteria = Object.entries(map.criteria);
  const scFiles = await readdir(join(wcagDir, "sc"));

  // WCAG 2.2 has 87 success-criterion sections; the reference should cover all
  // of them, and the criteria map and the per-SC files must agree.
  assert.ok(criteria.length >= 86, `only ${criteria.length} criteria mapped`);
  assert.equal(criteria.length, scFiles.length);
  assert.equal(Object.keys(map.tags).length, criteria.length);

  for (const [num, entry] of criteria) {
    // Each criterion points at a file that actually exists on disk.
    assert.equal(
      existsSync(join(wcagDir, entry.file)),
      true,
      `criterion ${num} -> missing file ${entry.file}`,
    );
    // axe tags a WCAG rule as `wcag` + the SC number with the dots removed. The
    // build must emit exactly that form or the axe enrichment cannot resolve.
    assert.equal(map.tags[`wcag${num.replaceAll(".", "")}`], num);
  }

  // Spot-check a well-known criterion end to end.
  assert.deepEqual(map.criteria["1.4.3"], {
    title: "Contrast (Minimum)",
    level: "AA",
    slug: "contrast-minimum",
    file: "sc/1.4.3-contrast-minimum.md",
  });
});

test("WCAG tree index links all resolve to criterion files", async () => {
  const index = await readFile(join(wcagDir, "index.md"), "utf8");
  const scFiles = await readdir(join(wcagDir, "sc"));

  // The index is the agent's discovery layer: principle -> guideline -> SC.
  assert.equal((index.match(/^## Principle /gm) || []).length, 4);
  assert.equal((index.match(/^### Guideline /gm) || []).length, 13);

  // Every SC in the tree links to a file, and every generated file is listed.
  const linked = [...index.matchAll(/`sc\/([^`]+\.md)`/g)].map((m) => m[1]);
  assert.equal(linked.length, scFiles.length);
  for (const file of linked) {
    assert.equal(
      existsSync(join(wcagDir, "sc", file)),
      true,
      `index links missing file sc/${file}`,
    );
  }
});

test("accessibility check enriches axe violations with their WCAG criterion", async () => {
  const runDir = await mkdtemp(join(tmpdir(), "tiny-rewrite-wcag-"));
  await mkdir(join(runDir, "screenshots"), { recursive: true });
  await writeFile(join(runDir, "facts.json"), JSON.stringify({ url: "" }));
  // One image with no alt text produces the `image-alt` axe violation, which
  // axe tags `wcag111` -> success criterion 1.1.1.
  await writeFile(
    join(runDir, "transformed.html"),
    `<!doctype html><html lang="en"><head><title>Alt text</title></head>` +
      `<body><main><h1>Alt text</h1><img src="${transparentGif}"></main></body></html>`,
  );

  // This runs the real production compaction path, not a copy of it.
  const result = await accessibilityProfile.check({ rootDir: runDir, runDir }, 1);
  const violation = result.axeViolations.find((v) => v.id === "image-alt");
  assert.ok(violation, "expected an image-alt axe violation");

  // The compact violation should now carry the WCAG criterion it maps to.
  assert.ok(Array.isArray(violation.wcag) && violation.wcag.length > 0);
  const sc = violation.wcag.find((entry) => entry.sc === "1.1.1");
  assert.ok(sc, "image-alt should map to success criterion 1.1.1");
  assert.match(sc.title, /Non-text Content/);
  assert.equal(sc.level, "A");

  // And the ref handed to the agent must resolve to the real criterion file.
  assert.equal(sc.ref, "reference/wcag/sc/1.1.1-non-text-content.md");
  const criterion = await readFile(join(repoRoot, sc.ref), "utf8");
  assert.match(criterion, /^# 1\.1\.1 Non-text Content/);
  assert.match(criterion, /## Requirement/);
});

test("an agent can locate a criterion by searching the tree index", async () => {
  // The swarm agents reach WCAG with their normal Read + Grep tools. This test
  // simulates that path deterministically: grep the tree for a concern, follow
  // the linked file, and confirm it holds the relevant normative text — the
  // same two steps an agent performs for an issue axe did not flag.
  const index = await readFile(join(wcagDir, "index.md"), "utf8");

  const hits = index.split("\n").filter((line) => /focus visible/i.test(line));
  assert.equal(hits.length, 1, "tree index should name Focus Visible once");

  const file = hits[0].match(/`sc\/([^`]+\.md)`/)[1];
  assert.equal(file, "2.4.7-focus-visible.md");

  const criterion = await readFile(join(wcagDir, "sc", file), "utf8");
  assert.match(criterion, /^# 2\.4\.7 Focus Visible/);
  assert.match(criterion, /- Level: AA/);
  assert.match(criterion, /## Requirement/);
  assert.match(criterion, /focus/i);
});
